### ISSUE TITLE
eth_getTransactionReceipt fails to find transaction

### ISSUE THREAD

**Issue by xBalbinus** [filecoin-project/fil-b#64]
**Description:**
Received similar query on TG on executing following command after setting up node.

curl --request POST \
  --url https://api.chain.love/rpc/v1https://api.chain.love/rpc/v1> \
  --header 'content-type: application/json' \
  --data '{
    "id": 0,
    "jsonrpc": "2.0",
    "method": "eth_getTransactionReceipt",
    "params": [
        "0x37690cfec6c1bf4c3b9288c7a5d783e98731e90b0a4c177c2a374c7a9427355e"
    ]
}'

**Source:**
https://filecoinproject.slack.com/archives/C0745JU645A/p1724224095219699?thread_ts=1724161038.363349&cid=C0745JU645A

**Comment by xBalbinus** [comment]
https://github.com/filecoin-project/lotus/issues/11583 Also see here

**Comment by trruckerfling** [comment]
https://github.com/filecoin-project/lotus/pull/12421 this seems to resolve things in ETH RPC API on Lotus. @xBalbinus @rk-rishikesh can either of you pls run tests to ensure this is resolved and not a builder issue moving forward?

**Comment by xBalbinus** [comment]
Followed up; issue still occurs, not sure if the curl req is wrong; the PRs seem to have gone through (at least partially)

**Comment by xBalbinus** [comment]
Update: PR was landed to fix, but chain.love has not updated their node to the latest version. Any action items on this should just relate to contacting these providers to update their services. Otherwise done.
